query SignatureStandings($tourCode: TourCode!) {
  signatureStandings(tourCode: $tourCode) {
    tournamentID
    infoTitle
    infoDescription
    official {
      title
      sponsorName
      description
      eyebrowText
      players {
        ... on SignaturePlayer {
          __typename
          playerId
          displayName
          shortName
          countryName
          countryFlag
          started
          projected
          projectedPoints
          movementAmount
          movementDirection
        }
        ... on SignatureInfoLine {
          __typename
          text
        }
      }
    }
    interim {
      title
      sponsorName
      description
      eyebrowText
      players {
        ... on SignaturePlayer {
          __typename
          playerId
          displayName
          shortName
          countryName
          countryFlag
          started
          projected
          projectedPoints
          movementAmount
          movementDirection
        }
        ... on SignatureInfoLine {
          __typename
          text
        }
      }
    }
  }
}
