query StatOverview($tourCode: TourCode!, $year: Int) {
  statOverview(tourCode: $tourCode, year: $year) {
    tourCode
    year
    categories {
      category
      displayName
      categoryType
      subCategories {
        displayName
        stats {
          statId
          statTitle
        }
      }
    }
    stats {
      statName
      tourAvg
      statId
      players {
        statId
        playerId
        statTitle
        statValue
        playerName
        rank
        country
        countryFlag
      }
    }
  }
}
